import React from 'react';
import { Html, Head, Body, Container, Section, Heading, Text, Hr } from '@react-email/components';

interface ScheduledReportEmailProps {
  reportName: string;
  period: string;
  totalPlants: number;
  totalCapacity: string;
  revenueAtRisk: string;
  riskLevel: string;
}

const styles = {
  body: {
    backgroundColor: '#f1f5f9',
    fontFamily: 'Arial, sans-serif',
  },
  container: {
    margin: '0 auto',
    padding: '20px 0 48px',
    width: '580px',
  },
  header: {
    backgroundColor: '#1e40af',
    borderRadius: '8px 8px 0 0',
    padding: '32px 40px',
  },
  brandName: {
    color: '#ffffff',
    fontSize: '24px',
    fontWeight: 'bold' as const,
    margin: '0 0 4px',
  },
  brandTagline: {
    color: '#93c5fd',
    fontSize: '13px',
    margin: '0',
  },
  section: {
    backgroundColor: '#ffffff',
    borderRadius: '0 0 8px 8px',
    padding: '32px 40px',
  },
  h2: {
    color: '#0f172a',
    fontSize: '20px',
    fontWeight: 'bold' as const,
    margin: '0 0 8px',
  },
  text: {
    color: '#374151',
    fontSize: '15px',
    lineHeight: '24px',
    margin: '0 0 16px',
  },
  metricsBox: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '20px 24px',
    margin: '16px 0 24px',
  },
  metricRow: {
    display: 'flex' as const,
    justifyContent: 'space-between' as const,
    padding: '6px 0',
    fontSize: '14px',
    color: '#334155',
  },
  metricLabel: {
    color: '#64748b',
    fontSize: '13px',
  },
  metricValue: {
    color: '#0f172a',
    fontSize: '14px',
    fontWeight: 'bold' as const,
  },
  hr: {
    borderColor: '#e2e8f0',
    margin: '24px 0',
  },
  footer: {
    color: '#94a3b8',
    fontSize: '12px',
    textAlign: 'center' as const,
    margin: '24px 0 0',
  },
};

const ScheduledReport: React.FC<Readonly<ScheduledReportEmailProps>> = ({
  reportName,
  period,
  totalPlants,
  totalCapacity,
  revenueAtRisk,
  riskLevel,
}) => (
  <Html>
    <Head />
    <Body style={styles.body}>
      <Container style={styles.container}>
        <Section style={styles.header}>
          <Heading style={styles.brandName}>NuraVolt</Heading>
          <Text style={styles.brandTagline}>Portfolio Intelligence Report</Text>
        </Section>
        <Section style={styles.section}>
          <Heading style={styles.h2}>{reportName}</Heading>
          <Text style={styles.text}>
            Your scheduled portfolio report for <strong>{period}</strong> is
            ready. The full report is attached as a PDF.
          </Text>

          <Section style={styles.metricsBox}>
            <table width="100%" cellPadding="0" cellSpacing="0" style={{ borderCollapse: 'collapse' }}>
              <tbody>
                <tr>
                  <td style={{ ...styles.metricLabel, padding: '6px 0' }}>Plants Monitored</td>
                  <td align="right" style={{ ...styles.metricValue, padding: '6px 0' }}>{totalPlants}</td>
                </tr>
                <tr>
                  <td style={{ ...styles.metricLabel, padding: '6px 0' }}>Total Capacity</td>
                  <td align="right" style={{ ...styles.metricValue, padding: '6px 0' }}>{totalCapacity}</td>
                </tr>
                <tr>
                  <td style={{ ...styles.metricLabel, padding: '6px 0' }}>Revenue at Risk</td>
                  <td align="right" style={{ ...styles.metricValue, padding: '6px 0', color: '#dc2626' }}>{revenueAtRisk}</td>
                </tr>
                <tr>
                  <td style={{ ...styles.metricLabel, padding: '6px 0' }}>Risk Level</td>
                  <td align="right" style={{ ...styles.metricValue, padding: '6px 0' }}>{riskLevel}</td>
                </tr>
              </tbody>
            </table>
          </Section>

          <Hr style={styles.hr} />

          <Text style={styles.footer}>
            This report was automatically generated by NuraVolt. To manage your
            report schedule, visit the Reports section of your dashboard.
          </Text>
        </Section>
      </Container>
    </Body>
  </Html>
);

export default ScheduledReport;
