/**
 * AOD Data Loader - Load merged CAMS EAC4 + Open-Meteo AOD data
 *
 * Loads pre-processed AOD data that combines:
 * - CAMS EAC4 Reanalysis (2020-2024): Research-grade historical data
 * - Open-Meteo CAMS Forecast (2025): Bias-corrected operational data
 *
 * Data files generated by: scripts/merge_aod_datasets.py
 */

export interface AODDataPoint {
  date: string;
  aod_550nm: number | null;  // Aerosol Optical Depth at 550nm (dimensionless)
}

export interface AODForecastPoint {
  date: string;
  aod_550nm_mean: number | null;
  aod_550nm_min: number | null;
  aod_550nm_max: number | null;
  hourly_count: number;
}

export interface AODMergedData {
  metadata: {
    plant_id: string;
    latitude: number;
    longitude: number;
    period: {
      start: string;
      end: string;
      total_days: number;
    };
    sources: {
      historical_2020_2024: string;
      recent_2025: string;
      bias_correction: number;
      validation_report: string;
    };
    generated_at: string;
    note: string;
  };
  statistics: {
    total_days: number;
    mean_aod: number;
    min_aod: number;
    max_aod: number;
  };
  daily_data: AODDataPoint[];
}

export interface AODForecastData {
  metadata: {
    plant_id: string;
    latitude: number;
    longitude: number;
    elevation?: number;
    forecast_period: {
      start: string;
      end: string;
      days: number;
    };
    source: string;
    bias_correction_applied: number;
    generated_at: string;
    note: string;
  };
  statistics: {
    forecast_days: number;
    mean_aod: number;
    min_aod: number;
    max_aod: number;
  };
  daily_forecast: AODForecastPoint[];
}

/**
 * Load merged AOD historical data (2020-present)
 *
 * @param plantId Plant identifier
 * @param dataRoot Optional base URL for data fetches (default: '/data').
 *   Pass '/data/showcase' when rendering inside the public showcase surface.
 */
export async function loadAODHistory(
  plantId: string,
  dataRoot: string = '/data',
): Promise<AODMergedData> {
  const response = await fetch(`${dataRoot}/soiling/${plantId}/aod_merged.json`);

  if (!response.ok) {
    throw new Error(`Failed to load AOD history for ${plantId}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Load AOD forecast (next 5 days)
 *
 * @param plantId Plant identifier
 * @param dataRoot Optional base URL for data fetches (default: '/data').
 */
export async function loadAODForecast(
  plantId: string,
  dataRoot: string = '/data',
): Promise<AODForecastData> {
  const response = await fetch(`${dataRoot}/soiling/${plantId}/aod_forecast.json`);

  if (!response.ok) {
    throw new Error(`Failed to load AOD forecast for ${plantId}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Load combined AOD data (history + forecast)
 */
export async function loadAODComplete(
  plantId: string,
  dataRoot: string = '/data',
): Promise<{
  history: AODMergedData;
  forecast: AODForecastData;
}> {
  const [history, forecast] = await Promise.all([
    loadAODHistory(plantId, dataRoot),
    loadAODForecast(plantId, dataRoot),
  ]);

  return { history, forecast };
}

/**
 * Get AOD data for a specific date range
 */
export function filterAODByDateRange(
  data: AODDataPoint[],
  startDate: string,
  endDate: string
): AODDataPoint[] {
  return data.filter(d => {
    return d.date >= startDate && d.date <= endDate;
  });
}

/**
 * Classify AOD level
 */
export function classifyAODLevel(aod: number): 'clean' | 'low' | 'moderate' | 'high' | 'very_high' {
  if (aod < 0.05) return 'clean';
  if (aod < 0.15) return 'low';
  if (aod < 0.30) return 'moderate';
  if (aod < 0.50) return 'high';
  return 'very_high';
}

/**
 * Get AOD level description and color
 */
export function getAODLevelInfo(aod: number): {
  label: string;
  color: string;
  impact: string;
  visibility: string;
} {
  const level = classifyAODLevel(aod);

  switch (level) {
    case 'clean':
      return {
        label: 'Clean Atmosphere',
        color: '#10B981',
        impact: 'Minimal soiling impact',
        visibility: '> 40 km',
      };
    case 'low':
      return {
        label: 'Low Aerosol',
        color: '#84CC16',
        impact: 'Low soiling accumulation',
        visibility: '20-40 km',
      };
    case 'moderate':
      return {
        label: 'Moderate Aerosol',
        color: '#FBBF24',
        impact: 'Moderate soiling, monitor conditions',
        visibility: '10-20 km',
      };
    case 'high':
      return {
        label: 'High Aerosol',
        color: '#F97316',
        impact: 'High soiling rate, cleaning may be needed',
        visibility: '5-10 km',
      };
    case 'very_high':
      return {
        label: 'Very High Aerosol',
        color: '#EF4444',
        impact: 'Severe soiling, cleaning recommended',
        visibility: '< 5 km',
      };
  }
}

/**
 * Calculate average AOD for a date range
 */
export function calculateAverageAOD(data: AODDataPoint[]): number {
  const validValues = data
    .filter(d => d.aod_550nm !== null)
    .map(d => d.aod_550nm!);

  if (validValues.length === 0) return 0;

  return validValues.reduce((sum, val) => sum + val, 0) / validValues.length;
}

/**
 * Find peak AOD days (above threshold)
 */
export function findPeakAODDays(
  data: AODDataPoint[],
  threshold: number = 0.3
): AODDataPoint[] {
  return data.filter(d => d.aod_550nm !== null && d.aod_550nm > threshold);
}

/**
 * Get data source information for a given date
 */
export function getDataSourceForDate(
  date: string,
  metadata: AODMergedData['metadata']
): 'CAMS EAC4 Reanalysis' | 'Open-Meteo CAMS Forecast' {
  // CAMS EAC4 covers through 2024-12-31
  // Open-Meteo covers 2025 onwards
  return date <= '2024-12-31' ? 'CAMS EAC4 Reanalysis' : 'Open-Meteo CAMS Forecast';
}

/**
 * Get bias correction information
 */
export function getBiasCorrectionInfo(plantId: string): {
  correction: number;
  description: string;
} {
  const corrections: Record<string, number> = {
    alpha1: 0.0020,
    eta: 0.0017,
    ribera: -0.0078,
  };

  const correction = corrections[plantId] || 0;

  return {
    correction,
    description: correction > 0
      ? `+${correction.toFixed(4)} added to Open-Meteo values`
      : correction < 0
      ? `${correction.toFixed(4)} subtracted from Open-Meteo values`
      : 'No bias correction needed',
  };
}
