#!/usr/bin/env python3
"""Generate docs/FAULT_COVERAGE.md: what backs each fault type, per fault.

Generated by inspecting the code, not hand-written, so it cannot drift from what
actually ships. For every member of ``FaultType`` it reports:

  * which detector method constructs the alert (or that none does)
  * the telemetry columns the detector looks for
  * the thresholds it uses and where each number came from
  * the tier: how well the claim travels to a plant we have not seen
  * whether any validation artifact covers it

Usage:
    python scripts/render_fault_coverage_doc.py
    python scripts/render_fault_coverage_doc.py --check
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from nuravolt.fault.rule_based import FaultType  # noqa: E402

RULE_BASED = REPO / "nuravolt" / "fault" / "rule_based.py"
SUMMARY = REPO / "public" / "data" / "validation" / "summary.json"
OUT = REPO / "docs" / "FAULT_COVERAGE.md"

# ---------------------------------------------------------------------------
# Tier: how well does this claim travel to an unseen plant?
#   A  peer-relative or self-referential; no portable constant exists to get wrong
#   B  anchored to physics, a standard, or a datasheet; not fitted to any dataset
#   C  fitted to a fleet; needs per-plant calibration and must be disclosed
# ---------------------------------------------------------------------------
TIERS: Dict[str, tuple] = {
    "INVERTER_OFFLINE": ("B", "Zero output during daylight is definitional, not fitted"),
    "INVERTER_CLIPPING": ("B", "Ratio against nameplate; nameplate is a datasheet fact"),
    "INVERTER_OVERTEMPERATURE": ("A", "Peer-relative since 2026-08-21: one machine hot against the siblings sharing its ambient. The absolute test now DECLINES unless the channel's semantics are declared, because the datasheet number is a rated ambient and the channel is usually a heatsink (measured p95 78.2 C in normal operation on delta, against a 60 C rated ambient)"),
    "INVERTER_EFFICIENCY_DEGRADATION": ("C", "92%/88% are fleet defaults, not per-model efficiency curves"),
    "DC_LINK_CAPACITOR_AGING": ("C", "Not emitted; specified only"),
    "DC_OVERVOLTAGE": ("B", "Datasheet MPPT window; refuses to run without it"),
    "DC_UNDERVOLTAGE": ("B", "Datasheet MPPT window; refuses to run without it"),
    "INVERTER_COOLING_DEGRADATION": ("C", "Thermal twin residual; needs a twin trained per plant"),
    "STRING_OPEN_CIRCUIT": ("A", "Peer ratio to the leave-one-out sibling median AND the modified z of the same comparison, sustained. No amp value anywhere in the path"),
    "STRING_SHORT_CIRCUIT": ("C", "Voltage ratio against a rolling baseline; partly self-referential"),
    "STRING_MISMATCH_COARSE": ("A", "The 0.85 ratio now has to clear the sibling DISPERSION too, which is what makes it mean the same thing on an array whose channels spread 2% and one that spreads 20%"),
    "STRING_DEGRADATION": ("C", "Digital twin residual; twin is per plant"),
    "MPPT_IMBALANCE": ("A", "Median and MAD over self-normalised channels; dimensionless throughout"),
    "MPPT_HUNTING": ("C", "Absolute 5 V oscillation and a count per hour"),
    "TRACKER_STUCK": ("B", "Angle variance near zero in daylight is definitional"),
    "TRACKER_MISALIGNED": ("B", "Deviation from computed solar position; astronomy, not fitting"),
    "GRID_FREQUENCY_LOW": ("B", "Grid code: 49.5 Hz"),
    "GRID_FREQUENCY_HIGH": ("B", "Grid code: 50.5 Hz"),
    "GRID_VOLTAGE_SAG": ("B", "Grid code: 90% of nominal"),
    "GRID_VOLTAGE_SWELL": ("B", "Grid code: 110% of nominal"),
    "GRID_CURTAILMENT": ("B", "Frequency offset triggering P-f response"),
    "EXPORT_CAP_ACTIVE": ("B", "Against the contracted export limit"),
    "MODULE_OVERTEMPERATURE": ("C", "85 C is a fleet default, not a module datasheet limit"),
    "MODULE_CURRENT_DEGRADATION": ("C", "Not emitted; superseded by the planned peer-relative rule"),
    "MODULE_VOLTAGE_DROP": ("C", "Not emitted; superseded by the planned peer-relative rule"),
    "BYPASS_DIODE_ACTIVE": ("C", "The comparison is peer-relative, but the band's LOWER EDGE (0.06) is set by dispersion measured on our own fleet, not by physics: the p90 MAD between healthy MPPT inputs is 0.0103 per-unit, so the one-diode signature of 1.1% is inside the noise. Needs re-measuring on a new plant, and single-diode detection needs string-level voltage this telemetry does not carry"),
    "COMMUNICATION_LOSS": ("B", "A data gap is definitional"),
    "COMMUNICATION_PARTIAL": ("B", "A channel that WAS reporting going null while its siblings continue is definitional. Judges device-local channels only: a shared pyranometer evaluated inside a per-inverter loop turned one outage into 28 alerts"),
    "SENSOR_FROZEN": ("A", "Run length of exactly identical consecutive values, gated to when the signal should be varying. Unit free, so it serves W/m2, degrees C and a power factor alike"),
    "IRRADIANCE_SENSOR_DRIFT": ("B", "Against a clear-sky model, which is astronomy plus atmosphere"),
    "SOILING_DETECTED": ("C", "PR below 0.95 is a fleet default; real soiling rates vary by climate"),
    "VEGETATION_SHADING": ("B", "Morning/afternoon asymmetry is geometric"),
    "INSULATION_RESISTANCE_LOW": ("B", "IEC 62446 limit"),
    "INVERTER_UNDERPERFORMANCE_PEER": ("A", "One machine below the median of the siblings on its bus, sustained. Irradiance, ambient, soiling, orientation and vendor all cancel because every peer meets them at the same instant"),
}

#: Which validation artifacts speak to which fault, and how directly.
VALIDATION: Dict[str, List[str]] = {
    "INVERTER_UNDERPERFORMANCE_PEER": [
        "pv/peer_inverter_underperformance_fleet.json (symmetric-tail null calibration)",
        "pv/rule_firing_rates_real_plants.json (firing rate on 4 real plants)"],
    "STRING_OPEN_CIRCUIT": ["pv/lazzaretti_holdout.json (F1 0.995, in-distribution)",
                            "pv/gpvs_cross_dataset.json (F1 0.000 cross-architecture)"],
    "STRING_SHORT_CIRCUIT": ["pv/lazzaretti_holdout.json (F1 0.983, in-distribution)",
                             "pv/gpvs_cross_dataset.json (F1 0.000 cross-architecture)"],
    "INVERTER_OVERTEMPERATURE": ["pv/gpvs_cross_dataset.json (F1 0.000 cross-architecture)"],
    "DC_LINK_CAPACITOR_AGING": ["pv/gpvs_cross_dataset.json (F1 0.565 cross-architecture)"],
    "GRID_VOLTAGE_SAG": ["pv/gpvs_cross_dataset.json (F1 0.631 cross-architecture)"],
    "GRID_VOLTAGE_SWELL": ["pv/gpvs_cross_dataset.json (F1 0.000 cross-architecture)"],
    "IRRADIANCE_SENSOR_DRIFT": ["pv/gpvs_cross_dataset.json (F1 0.000 cross-architecture)"],
    "SOILING_DETECTED": ["soiling/pvdaq_system_{2107,7334,9069}.json (IWSR 0.920-0.960 vs rdtools)",
                         "forecast/forecast_soiling_sr_ribera.json (1.44 pp vs reference sensor)"],
    "MODULE_CURRENT_DEGRADATION": ["pv/sandia_pv_iv_el_degradation.json (fleet fade vs literature)",
                                   "pv/rul_cross_dataset.json (Spearman -0.375, rank transfer only)"],
}

NOT_EMITTED_REASON = {
    "DC_LINK_CAPACITOR_AGING": "Specified, and the physics model exists, but no detector constructs the alert.",
    "MODULE_CURRENT_DEGRADATION": "Superseded by the planned peer-relative string deficit rule.",
    "MODULE_VOLTAGE_DROP": "Superseded by the planned peer-relative string voltage rule.",
}


def emit_map() -> Dict[str, Set[str]]:
    """Which methods actually CONSTRUCT a FaultAlert of each type."""
    src = RULE_BASED.read_text()
    tree = ast.parse(src)
    out: Dict[str, Set[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        seg = ast.get_source_segment(src, node) or ""
        for call in re.finditer(r"FaultAlert\((.*?)\)\s*[,\)]", seg, re.S):
            for ft in re.findall(r"FaultType\.([A-Z_]+)", call.group(1)):
                out.setdefault(ft, set()).add(node.name)
    return out


def signal_map() -> Dict[str, List[str]]:
    """Which telemetry columns each detector method searches for."""
    src = RULE_BASED.read_text()
    tree = ast.parse(src)
    out: Dict[str, List[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        seg = ast.get_source_segment(src, node) or ""
        found: Set[str] = set()
        for m in re.finditer(r"_find_column\w*\([^,]+,\s*\[(.*?)\]", seg, re.S):
            found.update(re.findall(r'"([^"]+)"', m.group(1)))
        out[node.name] = sorted(found)
    return out


def render() -> str:
    emits, signals = emit_map(), signal_map()
    summary = json.loads(SUMMARY.read_text()) if SUMMARY.exists() else {}
    gen = summary.get("generated_at", "unknown")

    total = len(list(FaultType))
    emitted = sum(1 for f in FaultType if f.name in emits)
    tier_counts: Dict[str, int] = {}
    for f in FaultType:
        tier_counts[TIERS.get(f.name, ("?", ""))[0]] = tier_counts.get(TIERS.get(f.name, ("?", ""))[0], 0) + 1

    L: List[str] = [
        "# Fault coverage, per fault",
        "",
        "> **Generated.** Run `python scripts/render_fault_coverage_doc.py` to rebuild from the",
        "> code. Do not edit by hand. The detector and signal columns are read out of",
        "> `nuravolt/fault/rule_based.py` by AST inspection, so they cannot drift from what",
        "> actually ships.",
        "",
        f"Validation snapshot: `{gen}`",
        "",
        f"**{total} fault types defined, {emitted} emitting, {total - emitted} specified but not emitting.**",
        "",
        f"By tier: {tier_counts.get('A', 0)} tier A, {tier_counts.get('B', 0)} tier B, "
        f"{tier_counts.get('C', 0)} tier C.",
        "",
        "## What the columns mean",
        "",
        "**Emits** — whether any code path actually constructs an alert of this type. Three types",
        "are defined and described but never raised; they are marked and must not be presented as",
        "live.",
        "",
        "**Tier** — how well the claim survives moving to a plant we have never seen. This is the",
        "most important column and it is the one to read first:",
        "",
        "| Tier | Meaning | Travels? |",
        "|---|---|---|",
        "| **A** | Peer-relative or self-referential. The device is judged against its own siblings at the same instant, so irradiance, temperature, plant size, orientation and vendor all cancel. There is no constant to carry to the next plant. | Yes, by construction |",
        "| **B** | Anchored to physics, a published standard, a grid code or a datasheet. Not fitted to any dataset of ours. | Yes, as far as the standard applies |",
        "| **C** | Fitted to our fleet. Needs per-plant calibration during onboarding, and must be disclosed as such. | Not without calibration |",
        "",
        "Why this matters, in one line: the same rule set scores macro-F1 **0.835** with thresholds",
        "tuned on a dataset, **0.519** with untuned physics defaults, and **0.189** on a different",
        "plant architecture. Roughly a third of the in-distribution score is threshold fitting. Tier",
        "is our estimate of which side of that gap a given fault sits on.",
        "",
        "**Signals** — the telemetry columns the detector searches for. Column matching is by",
        "substring, and a detector whose signal is absent returns silently, so a fault whose signals",
        "your SCADA does not expose is simply dark rather than failing loudly.",
        "",
        "**Validation** — an artifact under `public/data/validation/` that speaks to this fault. Most",
        "have none: only 7 of the 33 have any public-dataset ground truth at all, and 5 of those 7",
        "score F1 0.000 in the only cross-architecture test that has been run.",
        "",
        "---",
        "",
        "## Per fault",
        "",
        "| Fault | Emits | Tier | Why that tier | Signals | Validation |",
        "|---|---|---|---|---|---|",
    ]

    for f in FaultType:
        methods = sorted(emits.get(f.name, []))
        emits_txt = "yes" if methods else "**no**"
        tier, why = TIERS.get(f.name, ("?", "not classified"))
        sigs: Set[str] = set()
        for m in methods:
            sigs.update(signals.get(m, []))
        sig_txt = ", ".join(f"`{s}`" for s in sorted(sigs)[:4]) or "—"
        if len(sigs) > 4:
            sig_txt += f" +{len(sigs) - 4}"
        val = "<br>".join(VALIDATION.get(f.name, [])) or "—"
        if not methods:
            why = NOT_EMITTED_REASON.get(f.name, why)
        L.append(f"| `{f.name}` | {emits_txt} | **{tier}** | {why} | {sig_txt} | {val} |")

    L += [
        "",
        "---",
        "",
        "## The honest summary",
        "",
        f"- **{tier_counts.get('C', 0)} of {total} are tier C**: they carry a number fitted to our fleet and",
        "  will need calibration on a new site. That is the single biggest limitation of the current",
        "  detector set, and it is what the peer-relative work is replacing.",
        f"- **{total - emitted} are specified but never fire.** They are described in the code and were,",
        "  until recently, described to customers as live.",
        "- **Only 7 of 33 have any public-dataset ground truth**, and in the one cross-architecture",
        "  test, 5 of those 7 score F1 exactly 0.000, because the rules cannot express themselves on",
        "  a plant wired differently.",
        "- **Every emitting rule has now been measured on four real plants** "
        "(`pv/rule_firing_rates_real_plants.json`), not by precision -- real plants carry no "
        "labels -- but by comparing each rule's firing rate against a stated plausible bound "
        "for its failure mode. " + _firing_summary(),
        "- Peer-relative inverter underperformance is additionally null-calibrated across 416",
        "  inverters on 6 plants: the harmless tail of the same two-sided statistic gives a",
        "  false-positive estimate of 0.0020% against a theoretical 0.0032%, with signal 158x",
        "  the null.",
        "",
        "Nothing here is recall. Real plants carry no fault labels, so no number in this document",
        "says how many real faults were caught.",
        "",
    ]
    return "\n".join(L) + "\n"


def _firing_summary() -> str:
    """One sentence of live numbers from the firing-rate artifact, never hand-typed."""
    art = REPO / "public" / "data" / "validation" / "pv" / "rule_firing_rates_real_plants.json"
    if not art.exists():
        return "The artifact is not present in this checkout."
    d = json.loads(art.read_text())
    imp = d.get("implausible_rules") or []
    pr = d.get("peer_rewrite") or {}
    bits = []
    if pr.get("alerts_per_mw_month_after") is not None:
        bits.append(
            f"Fleet volume is {pr['alerts_per_mw_month_after']} alerts per MW-month, from "
            f"{pr['alerts_per_mw_month_before']} before the peer-relative rewrite."
        )
    bits.append(
        f"{len(imp)} rule(s) still fire above their bound"
        + (f": {', '.join('`' + r + '`' for r in imp)}." if imp else ".")
    )
    return " ".join(bits)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    body = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != body:
            print(f"{OUT} is stale; run scripts/render_fault_coverage_doc.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.write_text(body)
    print(f"wrote {OUT} ({len(body):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
