"""
BESS Fault Detector

Combines reactive warranty violation detection with predictive RUL models to
produce a unified, frontend-ready fault list for each BESS asset.

Reactive faults are sourced from WarrantyViolationDetector and mapped into
the same output schema as PV faults.  Predictive faults are generated by the
five BESS RUL models and include days-to-fault, confidence, and estimated
revenue impact.

Usage:
    from nuravolt.fault import BessFaultDetector

    detector = BessFaultDetector(electricity_price_eur_kwh=0.12)

    # asset_data: dict with keys described in _extract_history_df() docstrings
    # warranty_terms: dict matching WarrantyTermsConfig fields
    reactive  = detector.detect_reactive(asset_data)
    predictive = detector.predict_faults(asset_data, warranty_terms)

    all_faults = reactive + predictive
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Optional

from .bess_rul_models import (
    RULCapacityFadeModel,
    RULThermalStressModel,
    RULCycleLifeModel,
    RULRteDecayModel,
    RULCellImbalanceModel,
)

try:
    import pandas as pd
    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False


# ---------------------------------------------------------------------------
# Display metadata for each RUL model
# ---------------------------------------------------------------------------

_MODEL_META: dict[str, dict] = {
    "capacity_fade": {
        "display_name": "Capacity Fade Warning",
        "unit": "%",
        "recommended_action": (
            "Review dispatch strategy to reduce cycling stress and calendar aging"
        ),
        "energy_loss_factor": 1.0,   # fractional: scales with capacity loss
    },
    "thermal_stress": {
        "display_name": "Thermal Stress Warning",
        "unit": "°C",
        "recommended_action": (
            "Inspect HVAC / cooling system. Reduce peak power during hottest "
            "hours to lower cell temperature."
        ),
        "energy_loss_factor": 0.05,  # derating ~5% per thermal event
    },
    "cycle_life": {
        "display_name": "Cycle Life Warning",
        "unit": "EFC",
        "recommended_action": (
            "Reduce daily cycling frequency. Consider partial-cycle dispatching "
            "to stay within warranty budget."
        ),
        "energy_loss_factor": 0.0,   # opportunity cost only, not direct loss
    },
    "rte_decay": {
        "display_name": "Round-Trip Efficiency Decay",
        "unit": "%",
        "recommended_action": (
            "Investigate internal resistance increase. Check connections, BMS "
            "calibration, and consider capacity test to confirm degradation."
        ),
        "energy_loss_factor": 0.1,   # 10% round-trip loss reflected as energy loss
    },
    "cell_imbalance": {
        "display_name": "Cell Voltage Imbalance Warning",
        "unit": "mV",
        "recommended_action": (
            "Schedule a full balance cycle. If spread continues growing, "
            "inspect individual cells for early-stage failure."
        ),
        "energy_loss_factor": 0.02,  # mild capacity reduction from imbalance
    },
}

# Violation type → human-readable display name for reactive faults
_VIOLATION_DISPLAY: dict[str, str] = {
    "TEMPERATURE_EXCEED":    "Temperature Limit Exceeded",
    "SOC_HIGH_DWELL":        "Prolonged High SoC",
    "SOC_LOW_DWELL":         "Prolonged Low SoC",
    "CYCLING_DEPTH":         "Excessive Cycling Depth",
    "CYCLING_FREQUENCY":     "Excessive Cycling Frequency",
    "C_RATE_EXCEED":         "C-Rate Limit Exceeded",
    "VOLTAGE_VIOLATION":     "Cell Voltage Out of Bounds",
    "THROUGHPUT_EXCEED":     "Throughput Warranty Limit",
    "HVAC_FAILURE":          "HVAC System Failure",
    "RTE_DEGRADATION":       "Round-Trip Efficiency Degradation",
    "CAPACITY_DEGRADATION":  "Capacity Degradation Event",
}

_VIOLATION_ACTIONS: dict[str, str] = {
    "TEMPERATURE_EXCEED":    "Check HVAC, reduce power to lower cell temperature",
    "SOC_HIGH_DWELL":        "Dispatch energy to reduce SoC below 95%",
    "SOC_LOW_DWELL":         "Charge to safe SoC range above 20%",
    "CYCLING_DEPTH":         "Limit DoD to within warranty specification",
    "CYCLING_FREQUENCY":     "Reduce cycling rate; review dispatch schedule",
    "C_RATE_EXCEED":         "Derate power commands to stay within C-rate limit",
    "VOLTAGE_VIOLATION":     "Suspend charging/discharging; inspect BMS calibration",
    "THROUGHPUT_EXCEED":     "Contact manufacturer; review remaining warranty coverage",
    "HVAC_FAILURE":          "Emergency inspection of HVAC system required",
    "RTE_DEGRADATION":       "Conduct full capacity and efficiency test",
    "CAPACITY_DEGRADATION":  "Review SoH and initiate warranty claim process",
}


# ---------------------------------------------------------------------------
# BessFaultDetector
# ---------------------------------------------------------------------------

class BessFaultDetector:
    """
    Unified BESS fault detector combining reactive and predictive outputs.

    The detector produces output dicts matching the PV fault schema used by
    the frontend, making it straightforward to render BESS faults alongside
    inverter and module faults in the same dashboard panel.

    Args:
        electricity_price_eur_kwh: Market electricity price used to estimate
            revenue impact of detected faults.  Defaults to 0.10 EUR/kWh.
    """

    def __init__(self, electricity_price_eur_kwh: float = 0.10):
        self.electricity_price_eur_kwh = electricity_price_eur_kwh
        self.rul_models: dict[str, object] = {
            "capacity_fade": RULCapacityFadeModel(),
            "thermal_stress": RULThermalStressModel(),
            "cycle_life": RULCycleLifeModel(),
            "rte_decay": RULRteDecayModel(),
            "cell_imbalance": RULCellImbalanceModel(),
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def detect_reactive(self, asset_data: dict) -> list[dict]:
        """
        Convert WarrantyViolation objects embedded in asset_data into reactive
        fault dicts using the standard PV fault output schema.

        Args:
            asset_data: Dict that may contain:
                - 'violations': list of WarrantyViolation dataclass instances
                  (from nuravolt.bess.config.WarrantyViolation)
                - 'asset_id': str
                - 'asset_name': str
                - 'capacity_kwh': float

        Returns:
            List of reactive fault dicts.
        """
        violations = asset_data.get("violations", [])
        asset_id = str(asset_data.get("asset_id", "unknown"))
        asset_name = str(asset_data.get("asset_name", asset_id))
        capacity_kwh = float(asset_data.get("capacity_kwh", 1000.0))

        faults = []
        for idx, v in enumerate(violations):
            v_type = _get_field(v, "violation_type", "UNKNOWN")
            severity = _get_field(v, "severity", "warning")
            measured = _get_field(v, "measured_value", 0.0)
            threshold = _get_field(v, "threshold_value", 0.0)
            description = _get_field(v, "description", "")
            started_at = _get_field(v, "started_at", datetime.utcnow())
            unit = _get_field(v, "unit", "")

            display_name = _VIOLATION_DISPLAY.get(v_type, v_type.replace("_", " ").title())
            recommended_action = _VIOLATION_ACTIONS.get(
                v_type, "Investigate and resolve before next dispatch cycle"
            )

            urgency = "urgent" if severity == "critical" else "soon"
            power_loss_kw = self._reactive_power_loss(v_type, capacity_kwh, measured, threshold)
            energy_loss_kwh = power_loss_kw * 24.0  # rough daily estimate

            fault = {
                "id": f"bess-reactive-{v_type.lower()}-{asset_id}-{idx}",
                "fault_type": f"bess_{v_type.lower()}",
                "asset_type": "bess",
                "display_name": display_name,
                "equipment_id": asset_id,
                "equipment_name": asset_name,
                "urgency": urgency,
                "days_to_fault": 0.0,        # already a live violation
                "confidence": 1.0,           # rule-based, deterministic
                "current_value": float(measured),
                "threshold": float(threshold),
                "unit": unit,
                "recommended_action": recommended_action,
                "estimated_date": started_at.strftime("%Y-%m-%d")
                    if hasattr(started_at, "strftime") else str(started_at),
                "projected_power_loss_kw": round(power_loss_kw, 2),
                "projected_energy_loss_kwh": round(energy_loss_kwh, 1),
                "description": description,
                "severity": severity,
                "is_reactive": True,
            }
            faults.append(fault)

        return faults

    def predict_faults(
        self,
        asset_data: dict,
        warranty_terms: Optional[dict] = None,
    ) -> list[dict]:
        """
        Run all five RUL models and return predictive fault dicts.

        Args:
            asset_data: Dict containing:
                - 'asset_id': str
                - 'asset_name': str
                - 'capacity_kwh': float
                - 'soh_history': list of {'date': str, 'soh': float}
                - 'temp_history': list of {'date': str, 'daily_max_temp_c': float}
                - 'cycle_history': list of {'date': str, 'cumulative_efc': float}
                - 'rte_history': list of {'date': str, 'daily_rte': float}
                - 'imbalance_history': list of {'date': str, 'cell_voltage_spread_mv': float}
            warranty_terms: Optional dict of warranty overrides.  Recognised keys:
                - 'warranty_threshold' (float, default 0.70)
                - 'max_cycles' (int, default 6000)
                - 'min_rte' (float, default 0.85)
                - 'temp_limit_c' (float, default 45.0)
                - 'max_spread_mv' (float, default 50.0)

        Returns:
            List of predictive fault dicts (one per model with urgency != 'monitoring',
            plus all models that cross the urgency threshold).
        """
        if not HAS_PANDAS:
            raise ImportError("pandas is required for BessFaultDetector.predict_faults()")

        wt = warranty_terms or {}
        asset_id = str(asset_data.get("asset_id", "unknown"))
        asset_name = str(asset_data.get("asset_name", asset_id))
        capacity_kwh = float(asset_data.get("capacity_kwh", 1000.0))

        # Apply warranty overrides to models
        self._apply_warranty_overrides(wt)

        history_map = {
            "capacity_fade":  ("soh_history",        "soh"),
            "thermal_stress": ("temp_history",        "daily_max_temp_c"),
            "cycle_life":     ("cycle_history",       "cumulative_efc"),
            "rte_decay":      ("rte_history",         "daily_rte"),
            "cell_imbalance": ("imbalance_history",   "cell_voltage_spread_mv"),
        }

        faults = []
        today = datetime.utcnow().date()

        for model_name, model in self.rul_models.items():
            history_key, _ = history_map[model_name]
            raw_history = asset_data.get(history_key, [])

            if not raw_history:
                continue

            import pandas as pd  # already confirmed available
            history_df = pd.DataFrame(raw_history)

            try:
                prediction = model.predict(history_df)
            except Exception:
                continue

            if prediction["current_value"] is None:
                continue

            meta = _MODEL_META[model_name]
            days_to_fault = prediction["days_to_fault"]
            urgency = prediction["urgency"]
            confidence = prediction["confidence"]

            # Estimate revenue loss
            power_loss_kw, energy_loss_kwh = self._predictive_loss(
                model_name=model_name,
                days_to_fault=days_to_fault,
                capacity_kwh=capacity_kwh,
                current_value=prediction["current_value"],
                threshold=prediction["threshold"],
                meta=meta,
            )

            estimated_date = (
                today + timedelta(days=int(round(days_to_fault)))
            ).strftime("%Y-%m-%d")

            fault = {
                "id": f"bess-pred-{model_name}-{asset_id}",
                "fault_type": f"bess_{model_name}",
                "asset_type": "bess",
                "display_name": meta["display_name"],
                "equipment_id": asset_id,
                "equipment_name": asset_name,
                "urgency": urgency,
                "days_to_fault": days_to_fault,
                "confidence": confidence,
                "current_value": prediction["current_value"],
                "threshold": prediction["threshold"],
                "unit": meta["unit"],
                "recommended_action": meta["recommended_action"],
                "estimated_date": estimated_date,
                "projected_power_loss_kw": round(power_loss_kw, 2),
                "projected_energy_loss_kwh": round(energy_loss_kwh, 1),
                "trend": prediction["trend"],
                "is_urgent": prediction["is_urgent"],
                "is_reactive": False,
            }
            faults.append(fault)

        # Sort by urgency priority then days_to_fault ascending
        priority = {"urgent": 0, "soon": 1, "planned": 2, "monitoring": 3}
        faults.sort(key=lambda f: (priority.get(f["urgency"], 9), f["days_to_fault"]))

        return faults

    def compute_loss(
        self,
        fault: dict,
        capacity_kwh: float,
        price_eur_kwh: Optional[float] = None,
    ) -> float:
        """
        Estimate the projected revenue loss (EUR) for a single fault.

        Logic per fault type:
        - capacity_fade:  Lost arbitrage revenue = reduced capacity × daily
                          cycles × price.  Assumes 1 full cycle per day.
        - thermal_stress: Forced derating revenue loss = 5% of output × days
                          × capacity × price.
        - cycle_life:     Opportunity cost of cycling restrictions — assumes
                          reduction to 0.5 cycles/day × remaining days × price.
        - rte_decay:      Ongoing efficiency loss = (1 - rte) × energy × price.
        - cell_imbalance: Mild capacity penalty of 2% × remaining capacity × price.

        Args:
            fault: Fault dict as returned by predict_faults() or detect_reactive().
            capacity_kwh: Nominal battery capacity in kWh.
            price_eur_kwh: Override electricity price; defaults to instance value.

        Returns:
            Estimated revenue loss in EUR over the remaining useful life horizon.
        """
        price = price_eur_kwh if price_eur_kwh is not None else self.electricity_price_eur_kwh
        fault_type = fault.get("fault_type", "")
        current_value = fault.get("current_value") or 0.0
        threshold = fault.get("threshold") or 0.0
        days_to_fault = float(fault.get("days_to_fault") or 0.0)

        if "capacity_fade" in fault_type:
            # Lost capacity = (1 - current_soh) × capacity_kwh
            # Assumes 1 full cycle/day arbitrage
            lost_capacity_kwh = max(0.0, (1.0 - current_value)) * capacity_kwh
            return round(lost_capacity_kwh * days_to_fault * price, 2)

        if "thermal_stress" in fault_type:
            # 5% derating for days above thermal limit
            derating_kwh_per_day = capacity_kwh * 0.05
            return round(derating_kwh_per_day * days_to_fault * price, 2)

        if "cycle_life" in fault_type:
            # Opportunity cost: restrict cycling to 0.5 cycles/day vs. normal 1.0
            restricted_loss_kwh_per_day = capacity_kwh * 0.5
            return round(restricted_loss_kwh_per_day * days_to_fault * price, 2)

        if "rte_decay" in fault_type:
            # Efficiency gap × daily throughput (assume 1 cycle = 2× capacity)
            rte_gap = max(0.0, threshold - current_value)  # threshold = min_rte
            daily_loss_kwh = capacity_kwh * 2.0 * rte_gap
            return round(daily_loss_kwh * days_to_fault * price, 2)

        if "cell_imbalance" in fault_type:
            # 2% capacity penalty
            penalty_kwh = capacity_kwh * 0.02
            return round(penalty_kwh * days_to_fault * price, 2)

        # Default: use projected energy loss field if present
        energy_loss = float(fault.get("projected_energy_loss_kwh") or 0.0)
        return round(energy_loss * price, 2)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _apply_warranty_overrides(self, wt: dict) -> None:
        """Push warranty override values into the instantiated RUL models."""
        if "warranty_threshold" in wt:
            self.rul_models["capacity_fade"].warranty_threshold = float(
                wt["warranty_threshold"]
            )
        if "max_cycles" in wt:
            self.rul_models["cycle_life"].max_cycles = float(wt["max_cycles"])
        if "min_rte" in wt:
            self.rul_models["rte_decay"].min_rte = float(wt["min_rte"])
        if "temp_limit_c" in wt:
            self.rul_models["thermal_stress"].temp_limit_c = float(wt["temp_limit_c"])
        if "max_spread_mv" in wt:
            self.rul_models["cell_imbalance"].max_spread_mv = float(wt["max_spread_mv"])

    def _reactive_power_loss(
        self,
        v_type: str,
        capacity_kwh: float,
        measured: float,
        threshold: float,
    ) -> float:
        """Estimate power loss kW for a reactive violation."""
        if "TEMPERATURE" in v_type or "HVAC" in v_type:
            # Forced derating at ~5% per °C above threshold
            delta = max(0.0, measured - threshold)
            derate_fraction = min(0.5, delta * 0.05)
            nominal_power_kw = capacity_kwh  # rough 1C assumption
            return nominal_power_kw * derate_fraction

        if "C_RATE" in v_type:
            # Clamp to allowable power; loss = excess × capacity
            excess = max(0.0, measured - threshold)
            return excess * capacity_kwh

        if "VOLTAGE" in v_type:
            # Hard derating: assume 10% capacity loss
            return capacity_kwh * 0.10

        return 0.0

    def _predictive_loss(
        self,
        model_name: str,
        days_to_fault: float,
        capacity_kwh: float,
        current_value: float,
        threshold: float,
        meta: dict,
    ) -> tuple[float, float]:
        """
        Return (projected_power_loss_kw, projected_energy_loss_kwh) for a
        predictive fault prior to fault materialisation.
        """
        factor = meta.get("energy_loss_factor", 0.0)

        if model_name == "capacity_fade":
            # Already lost capacity from SoH degradation
            lost_fraction = max(0.0, 1.0 - current_value)
            power_loss_kw = capacity_kwh * lost_fraction  # 1C assumption
            energy_loss_kwh = power_loss_kw * 24.0
            return power_loss_kw, energy_loss_kwh

        if model_name == "thermal_stress":
            power_loss_kw = capacity_kwh * factor
            energy_loss_kwh = power_loss_kw * 24.0
            return power_loss_kw, energy_loss_kwh

        if model_name == "rte_decay":
            rte_gap = max(0.0, threshold - current_value)
            daily_loss = capacity_kwh * 2.0 * rte_gap
            power_loss_kw = daily_loss / 24.0
            return power_loss_kw, daily_loss

        if model_name == "cell_imbalance":
            power_loss_kw = capacity_kwh * factor
            energy_loss_kwh = power_loss_kw * 24.0
            return power_loss_kw, energy_loss_kwh

        # cycle_life: opportunity cost, no direct power loss
        return 0.0, 0.0


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _get_field(obj, field: str, default):
    """Read a field from a dataclass instance or plain dict."""
    if isinstance(obj, dict):
        return obj.get(field, default)
    return getattr(obj, field, default)
