'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import DashboardCanvas from '@/components/reports/DashboardCanvas';
import ScopeBar from '@/components/reports/ScopeBar';
import type { DashboardScope, DashboardWidget, DateRangePreset } from '@/types/dashboard';

/** Chip labels for the read-only scope bar: the dashboard's own plant scope
 *  (a public viewer has no /api/plants access, and fixture names here leaked
 *  another portfolio's plants into shared views and PDFs). */
function chipsFor(plantIds: string[]) {
  return plantIds.map((id) => ({
    plantId: id,
    plantName: id
      .split(/[-_]/)
      .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
      .join(' '),
  }));
}

/**
 * Public read-only dashboard view. No auth, no chrome.
 * Rendered at /r/[token]; the dashboard owner creates/revokes the token
 * from the editor's Share button.
 */
export default function PublicDashboardPage() {
  const params = useParams();
  const token = decodeURIComponent(params.token as string);
  const [title, setTitle] = useState('');
  const [widgets, setWidgets] = useState<DashboardWidget[]>([]);
  const [scope, setScope] = useState<DashboardScope>({
    plantIds: [],
    deviceIds: [],
    range: 'last_30d',
    from: null,
    to: null,
  });
  const [status, setStatus] = useState<'loading' | 'ok' | 'not-found' | 'expired'>('loading');

  useEffect(() => {
    fetch(`/api/dashboards/public/${token}`)
      .then((r) => {
        if (r.status === 404) return { status: 'not-found' as const };
        if (r.status === 410) return { status: 'expired' as const };
        if (!r.ok) return { status: 'not-found' as const };
        return r.json().then((j) => ({ status: 'ok' as const, data: j.data }));
      })
      .then((res) => {
        if (res.status !== 'ok') {
          setStatus(res.status);
          return;
        }
        const d = res.data;
        setTitle(d.title);
        setWidgets(Array.isArray(d.widgets) ? d.widgets : []);
        setScope({
          plantIds: d.scope_plant_ids ?? [],
          deviceIds: d.scope_device_ids ?? [],
          range: (d.default_range as DateRangePreset) ?? 'last_30d',
          from: d.default_from,
          to: d.default_to,
        });
        setStatus('ok');
      })
      .catch(() => setStatus('not-found'));
  }, [token]);

  if (status === 'loading') {
    return <div className="p-8 text-sm text-gray-500">Loading dashboard…</div>;
  }
  if (status === 'not-found') {
    return (
      <div className="flex items-center justify-center min-h-screen text-center p-8">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Dashboard not found</h1>
          <p className="text-sm text-gray-500 mt-2">
            This share link has been revoked or never existed.
          </p>
        </div>
      </div>
    );
  }
  if (status === 'expired') {
    return (
      <div className="flex items-center justify-center min-h-screen text-center p-8">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Share link expired</h1>
          <p className="text-sm text-gray-500 mt-2">
            Ask the dashboard owner for a fresh link.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-[1400px] mx-auto p-6 space-y-4">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
        <p className="text-xs text-gray-400 mt-0.5">Shared via NuraVolt</p>
      </div>
      <ScopeBar scope={scope} onChange={setScope} availablePlants={chipsFor(scope.plantIds)} readOnly />
      <DashboardCanvas scope={scope} widgets={widgets} readOnly />
      <div className="text-center text-xs text-gray-400 pt-6">
        Generated by NuraVolt
      </div>
    </div>
  );
}
